/* ============================================================================
   Author: ENG Ahmed Hassan
   Origin: SalesforceDW_Structure_Only.sql (2026-07-26 SSMS structure export)
   ============================================================================ */

/* Environment-specific database + settings from the 2026-07-26 export.
   OPTIONAL: review file paths (F:\...) before running on a new server. */
USE [master];
GO
USE [master]
GO
CREATE DATABASE [SalesforceDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SalesforceDW', FILENAME = N'F:\ahmed\sql server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SalesforceDW.mdf' , SIZE = 70721536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SalesforceDW_log', FILENAME = N'F:\ahmed\sql server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SalesforceDW_log.ldf' , SIZE = 794624KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SalesforceDW] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SalesforceDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SalesforceDW] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [SalesforceDW] SET ANSI_NULLS OFF
GO
ALTER DATABASE [SalesforceDW] SET ANSI_PADDING OFF
GO
ALTER DATABASE [SalesforceDW] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [SalesforceDW] SET ARITHABORT OFF
GO
ALTER DATABASE [SalesforceDW] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [SalesforceDW] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [SalesforceDW] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [SalesforceDW] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [SalesforceDW] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [SalesforceDW] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [SalesforceDW] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [SalesforceDW] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [SalesforceDW] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [SalesforceDW] SET  ENABLE_BROKER
GO
ALTER DATABASE [SalesforceDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [SalesforceDW] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [SalesforceDW] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SalesforceDW] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [SalesforceDW] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [SalesforceDW] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [SalesforceDW] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [SalesforceDW] SET RECOVERY FULL
GO
ALTER DATABASE [SalesforceDW] SET  MULTI_USER
GO
ALTER DATABASE [SalesforceDW] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [SalesforceDW] SET DB_CHAINING OFF
GO
ALTER DATABASE [SalesforceDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [SalesforceDW] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [SalesforceDW] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [SalesforceDW] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'SalesforceDW', N'ON'
GO
ALTER DATABASE [SalesforceDW] SET QUERY_STORE = ON
GO
ALTER DATABASE [SalesforceDW] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SalesforceDW]
GO
