/* ============================================================================
   Author: ENG Ahmed Hassan
   Origin: SalesforceDW_Structure_Only.sql (2026-07-26 SSMS structure export)
   ============================================================================ */

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [raw].[salesforce_payment](
	[Id] [varchar](max) NULL,
	[IsDeleted] [varchar](max) NULL,
	[Name] [varchar](max) NULL,
	[CurrencyIsoCode] [varchar](max) NULL,
	[RecordTypeId] [varchar](max) NULL,
	[CreatedDate] [varchar](max) NULL,
	[CreatedById] [varchar](max) NULL,
	[LastModifiedDate] [varchar](max) NULL,
	[LastModifiedById] [varchar](max) NULL,
	[SystemModstamp] [varchar](max) NULL,
	[LastViewedDate] [varchar](max) NULL,
	[LastReferencedDate] [varchar](max) NULL,
	[npe01__Opportunity__c] [varchar](max) NULL,
	[npe01__Check_Reference_Number__c] [varchar](max) NULL,
	[npe01__Custom_Payment_Field__c] [varchar](max) NULL,
	[npe01__Paid__c] [varchar](max) NULL,
	[npe01__Payment_Amount__c] [varchar](max) NULL,
	[npe01__Payment_Date__c] [varchar](max) NULL,
	[npe01__Payment_Method__c] [varchar](max) NULL,
	[npe01__Scheduled_Date__c] [varchar](max) NULL,
	[npe01__Written_Off__c] [varchar](max) NULL,
	[npsp__Payment_Acknowledged_Date__c] [varchar](max) NULL,
	[npsp__Payment_Acknowledgment_Status__c] [varchar](max) NULL,
	[npsp__Authorized_Date__c] [varchar](max) NULL,
	[npsp__Authorized_UTC_Timestamp__c] [varchar](max) NULL,
	[npsp__Card_Expiration_Month__c] [varchar](max) NULL,
	[npsp__Card_Expiration_Year__c] [varchar](max) NULL,
	[npsp__Card_Last_4__c] [varchar](max) NULL,
	[npsp__Card_Network__c] [varchar](max) NULL,
	[npsp__Elevate_Original_Payment_ID__c] [varchar](max) NULL,
	[npsp__Elevate_Payment_Created_Date__c] [varchar](max) NULL,
	[npsp__Elevate_Payment_Created_UTC_Timestamp__c] [varchar](max) NULL,
	[npsp__Elevate_Payment_ID__c] [varchar](max) NULL,
	[npsp__Gateway_ID__c] [varchar](max) NULL,
	[npsp__Gateway_Payment_ID__c] [varchar](max) NULL,
	[npsp__Origin_ID__c] [varchar](max) NULL,
	[npsp__Origin_Name__c] [varchar](max) NULL,
	[npsp__Origin_Type__c] [varchar](max) NULL,
	[npsp__Type__c] [varchar](max) NULL,
	[npsp__Donor_Cover_Amount__c] [varchar](max) NULL,
	[npsp__Batch_Number__c] [varchar](max) NULL,
	[npsp__ACH_Last_4__c] [varchar](max) NULL,
	[Payment_Stage__c] [varchar](max) NULL,
	[npsp__ACH_Code__c] [varchar](max) NULL,
	[npsp__Elevate_Payment_API_Declined_Reason__c] [varchar](max) NULL,
	[npsp__Elevate_Payment_API_Status__c] [varchar](max) NULL,
	[Income_Debit_History__c] [varchar](max) NULL,
	[Authorisation_Code__c] [varchar](max) NULL,
	[Bank_Notes__c] [varchar](max) NULL,
	[Card_Payment_History__c] [varchar](max) NULL,
	[Card_Type__c] [varchar](max) NULL,
	[Contact__c] [varchar](max) NULL,
	[Deposit_Bank_Account__c] [varchar](max) NULL,
	[Deposit_Date__c] [varchar](max) NULL,
	[Deposit_Pay_Slip__c] [varchar](max) NULL,
	[Gateway_Customer_Reference__c] [varchar](max) NULL,
	[Gift_Aid_Precluded__c] [varchar](max) NULL,
	[Name_On_Card__c] [varchar](max) NULL,
	[Order_ID__c] [varchar](max) NULL,
	[Payment_Reference__c] [varchar](max) NULL,
	[Payment_Vendor__c] [varchar](max) NULL,
	[Postal_Order__c] [varchar](max) NULL,
	[Status__c] [varchar](max) NULL,
	[Transaction_ID__c] [varchar](max) NULL,
	[Transaction_Source__c] [varchar](max) NULL,
	[Transaction_Type__c] [varchar](max) NULL,
	[DMS_DonationPayment_ID__c] [varchar](max) NULL,
	[Payment_Description__c] [varchar](max) NULL,
	[npsp__Elevate_Transaction_Fee__c] [varchar](max) NULL,
	[npsp__Gateway_Transaction_Fee__c] [varchar](max) NULL,
	[npsp__Total_Transaction_Fees__c] [varchar](max) NULL,
	[Reason_for_Refund__c] [varchar](max) NULL,
	[Amount_Decimal__c] [varchar](max) NULL,
	[AUDDIS_Ref__c] [varchar](max) NULL,
	[Card_Details__c] [varchar](max) NULL,
	[Payment_Status__c] [varchar](max) NULL,
	[Amount__c] [varchar](max) NULL,
	[Payment__c] [varchar](max) NULL,
	[Payout_Id__c] [varchar](max) NULL,
	[Exchange_Rate__c] [varchar](max) NULL,
	[Agency_Fees__c] [varchar](max) NULL,
	[_etl_run_id] [bigint] NULL,
	[_etl_extracted_at_utc] [datetime] NULL,
	[_etl_source_object] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
