"""
Merge SQL deploy scripts into one ordered output file.

Reads execution order from a sqlcmd deploy file (default: database/_deploy.sql),
expands :r include directives recursively, and writes one merged SQL script.

Usage examples:
  python Quality_layer_check/scripts/merge_sql_deploy.py
  python Quality_layer_check/scripts/merge_sql_deploy.py --verbose
  python Quality_layer_check/scripts/merge_sql_deploy.py --output Quality_layer_check/database/deploy_full_merged.sql
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


DEFAULT_DEPLOY = Path("Quality_layer_check/database/_deploy.sql")
DEFAULT_OUTPUT = Path("Quality_layer_check/database/deploy_merged.sql")
DEFAULT_EXTRA_FILES = [
    Path("Quality_layer_check/DQ Frame work/DQ_framework_creation_incremental.sql"),
    Path("Quality_layer_check/DQ Frame work/DQ_framework_seed_checks_from_existing_prod.sql"),
]


def to_path(include_expr: str) -> Path:
    """Normalize sqlcmd include path to current OS separators."""
    return Path(include_expr.replace("\\", "/"))


def load_text(file_path: Path) -> str:
    return file_path.read_text(encoding="utf-8-sig")


def parse_include(line: str) -> str | None:
    stripped = line.lstrip()
    if not stripped.lower().startswith(":r"):
        return None
    parts = stripped.split(maxsplit=1)
    if len(parts) < 2:
        return None
    include = parts[1].strip()
    if include.startswith('"') and include.endswith('"') and len(include) >= 2:
        include = include[1:-1]
    return include


def expand_sql_file(
    file_path: Path,
    ordered_files: list[Path],
    seen_stack: set[Path],
    verbose: bool,
) -> None:
    resolved = file_path.resolve()
    if resolved in seen_stack:
        cycle = " -> ".join(str(p) for p in [*seen_stack, resolved])
        raise RuntimeError(f"Circular include detected: {cycle}")

    if not resolved.exists():
        raise FileNotFoundError(f"Include file not found: {resolved}")

    seen_stack.add(resolved)
    if verbose:
        print(f"Reading: {resolved}")

    for line in load_text(resolved).splitlines():
        include_expr = parse_include(line)
        if include_expr is None:
            continue
        include_path = (resolved.parent / to_path(include_expr)).resolve()
        expand_sql_file(include_path, ordered_files, seen_stack, verbose)

    seen_stack.remove(resolved)

    # Include files are appended when fully expanded so ordering stays stable.
    # We only append non-driver sql files (the deploy file itself is added by caller
    # only when explicitly requested).
    ordered_files.append(resolved)


def format_section(file_path: Path, text: str, project_root: Path) -> str:
    try:
        display = file_path.relative_to(project_root)
    except ValueError:
        display = file_path

    header = (
        "\n\n"
        "/* ============================================================================\n"
        f"   BEGIN FILE: {display.as_posix()}\n"
        "   ============================================================================ */\n"
    )
    footer = (
        "\n"
        "/* ============================================================================\n"
        f"   END FILE: {display.as_posix()}\n"
        "   ============================================================================ */\n"
    )
    return header + text.rstrip() + "\n" + footer


def merge_scripts(
    project_root: Path,
    deploy_sql: Path,
    output_sql: Path,
    include_extra_framework: bool,
    verbose: bool,
) -> list[Path]:
    deploy_path = (project_root / deploy_sql).resolve()
    output_path = (project_root / output_sql).resolve()

    if not deploy_path.exists():
        raise FileNotFoundError(f"Deploy script not found: {deploy_path}")

    ordered: list[Path] = []
    expand_sql_file(deploy_path, ordered, set(), verbose)

    # The recursive expansion appends the root deploy script too; we do not want
    # deploy-driver directives in the final merged output.
    ordered = [p for p in ordered if p != deploy_path]

    if include_extra_framework:
        for rel in DEFAULT_EXTRA_FILES:
            extra = (project_root / rel).resolve()
            if not extra.exists():
                raise FileNotFoundError(f"Framework script not found: {extra}")
            ordered.append(extra)

    seen: set[Path] = set()
    deduped: list[Path] = []
    for p in ordered:
        if p in seen:
            continue
        seen.add(p)
        deduped.append(p)

    preamble = (
        "/* ============================================================================\n"
        "   AUTO-GENERATED FILE: deploy_merged.sql\n"
        "   Generated by: Quality_layer_check/scripts/merge_sql_deploy.py\n"
        "\n"
        "   Notes:\n"
        "   - Order is sourced from database/_deploy.sql include directives.\n"
        "   - DQ framework scripts are appended at the end by default.\n"
        "   - Review before running in production.\n"
        "   ============================================================================ */\n"
        "SET NOCOUNT ON;\nGO\n"
    )

    merged = [preamble]
    for file_path in deduped:
        merged.append(format_section(file_path, load_text(file_path), project_root))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(merged), encoding="utf-8")
    return deduped


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Merge SQL files in deploy order into one script."
    )
    parser.add_argument(
        "--project-root",
        default=".",
        help="Workspace root path (default: current directory).",
    )
    parser.add_argument(
        "--deploy",
        default=str(DEFAULT_DEPLOY),
        help="Path to sqlcmd deploy driver file (default: Quality_layer_check/database/_deploy.sql).",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Output path for merged SQL file (default: Quality_layer_check/database/deploy_merged.sql).",
    )
    parser.add_argument(
        "--no-extra-framework",
        action="store_true",
        help="Do not append DQ framework SQL files after deploy order.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print each file as it is processed.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    try:
        merged_files = merge_scripts(
            project_root=Path(args.project_root),
            deploy_sql=Path(args.deploy),
            output_sql=Path(args.output),
            include_extra_framework=not args.no_extra_framework,
            verbose=args.verbose,
        )
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print("Merged SQL file created successfully.")
    print(f"Output: {Path(args.output).as_posix()}")
    print(f"Files merged: {len(merged_files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
